# Generated by Django 5.1.6 on 2025-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='answer',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='question',
            field=models.TextField(default='N/A'),
        ),
    ]
