# Generated by Django 5.1.6 on 2025-02-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0003_auto_20250207_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
